version: '3'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"  # Exposes port 3000 on the host, but internal communication uses the service name

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api
