version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - api
