version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - api
