# Use the official Node.js image as a base image
FROM node:latest

# Set the working directory in the container
WORKDIR /api

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY api/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY api/ ./

# Expose the port on which the app will run
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
