name: Deploy Nodejs Application

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }}  -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build api docker image
        run: docker build -t harshkvr7/api ./api  
      - name: Publish api image to docker hub
        run: docker push harshkvr7/api:latest
      - name: Build client docker image
        run: docker build -t harshkvr7/client ./client  
      - name: Publish client image to docker hub
        run: docker push harshkvr7/client:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull api image from docker hub
        run: sudo docker pull harshkvr7/api:latest
      - name: Pull client image from docker hub
        run: sudo docker pull harshkvr7/client:latest
      - name: Delete old containers
        run: sudo docker compose down
      - name: cd to Blog3 folder
        run: cd Blog3
      - name: Run docker container
        run: sudo docker compose up
